# Generated by Django 5.2.12 on 2026-04-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_auditlog_details_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarizeddocument',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='summary_files/'),
        ),
    ]
