# Generated by Django 5.2.12 on 2026-04-13 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_summarizeddocument_file_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='sharedmaterial',
            name='helpful',
            field=models.ManyToManyField(blank=True, related_name='helpful_materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
