# Generated by Django 5.2.12 on 2026-04-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_quiz_is_mastered_quiz_score_task_reflection'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='user_answers',
            field=models.JSONField(blank=True, help_text="Stores the user's selected answers", null=True),
        ),
    ]
